const data = {
  products: [
    {
      _id: "1",
      name: "Aglonema Red",
      category: "Foliage Plants",
      image: "/images/aglonema-red.jpg",
      price: 150,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "2",
      name: "Aglonema Green",
      category: "Foliage Plants",
      image: "/images/aglonema-green.jpg",
      price: 150,
      countInStock: 10,
      rating: 3.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "3",
      name: "Marginata Green",
      category: "Foliage Plants",
      image: "/images/marginata-green.jpg",
      price: 120,
      countInStock: 10,
      rating: 4,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "4",
      name: "Marginata Red",
      category: "Foliage Plants",
      image: "/images/marginata-red.jpg",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "5",
      name: "Money Plant",
      category: "Foliage Plants",
      image: "/images/money-plant.jpg",
      price: 150,
      countInStock: 10,
      rating: 5,
      numReviews: 10,
      description: "high quality products",
    },

    {
      _id: "6",
      name: "Rubber Plant",
      category: "Foliage Plants",
      image: "/images/rubber-plant.jpg",
      price: 250,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "7",
      name: "Coleus (Red)",
      category: "Foliage Plants",
      image: "/images/coleus.jpg",
      price: 100,
      countInStock: 10,
      rating: 4,
      numReviews: 10,
      description: "high quality products",
    },

    {
      _id: "8",
      name: "Thuja (Golden)",
      category: "Foliage Plants",
      image: "/images/thuja-golden.jpg",
      price: 120,
      countInStock: 10,
      rating: 3,
      numReviews: 10,
      description: "high quality products",
    },

    {
      _id: "9",
      name: "Croton",
      category: "Foliage Plants",
      image: "/images/croton.jpg",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "10",
      name: "Chrysanthemum (Shevanti) - Yellow",
      category: "Foliage Plants",
      image: "/images/chrysanthemum-yellow.jpg",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },

    {
      _id: "11",
      name: "Chrysanthemum (Shevanti) - White",
      category: "Foliage Plants",
      image: "/images/crysanthemum-white.jpg",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "12",
      name: "Thuja",
      category: "Foliage Plants",
      image: "/images/thuja.jpg",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      _id: "13",
      name: "NJoy Pothos",
      category: "Foliage Plants",
      image: "/images/njoy-pothos.jpg",
      price: 150,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
  ],
};

export default data;
