import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Sushil",
      email: "sushilrindhe29@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "rushab",
      email: "sushilrindhe324@gmail.com",
      password: bcrypt.hashSync("123", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Aglonema Red",
      category: "Foliage Plants",
      image: "/images/aglonema-red.jpg",
      price: 200,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "Aglonema Green",
      category: "Foliage Plants",
      image: "/images/aglonema-green.jpg",
      price: 200,
      countInStock: 8,
      rating: 3.5,
      numReviews: 40,
      description: "high quality products",
    },
    {
      name: "Marginata Green",
      category: "Foliage Plants",
      image: "/images/marginata-green.jpg",
      price: 100,
      countInStock: 10,
      rating: 4,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "Marginata Red",
      category: "Foliage Plants",
      image: "/images/marginata-red.jpg",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "Money Plant",
      category: "Foliage Plants",
      image: "/images/money-plant.jpg",
      price: 150,
      countInStock: 10,
      rating: 5,
      numReviews: 10,
      description: "high quality products",
    },

    {
      name: "Rubber Plant",
      category: "Foliage Plants",
      image: "/images/rubber-plant.jpg",
      price: 250,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "Coleus (Red)",
      category: "Foliage Plants",
      image: "/images/coleus.jpg",
      price: 100,
      countInStock: 10,
      rating: 4,
      numReviews: 10,
      description: "high quality products",
    },

    {
      name: "Thuja (Golden)",
      category: "Foliage Plants",
      image: "/images/thuja-golden.jpg",
      price: 120,
      countInStock: 10,
      rating: 3,
      numReviews: 10,
      description: "high quality products",
    },

    {
      name: "Croton",
      category: "Foliage Plants",
      image: "/images/croton.jpg",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "Chrysanthemum - Yellow",
      category: "Foliage Plants",
      image: "/images/chrysanthemum-yellow.jpg",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },

    {
      name: "Chrysanthemum - White",
      category: "Foliage Plants",
      image: "/images/crysanthemum-white.jpg",
      price: 100,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "Thuja",
      category: "Foliage Plants",
      image: "/images/thuja.jpg",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "NJoy Pothos",
      category: "Foliage Plants",
      image: "/images/njoy-pothos.jpg",
      price: 150,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
  ],
};

export default data;
